spring:
  config:
    import: naver-sms.properties

  datasource:
    url: jdbc:mysql://j8a408.p.ssafy.io:3306/carmingdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: carming
    password: carming123

  redis:
    host: j8a408.p.ssafy.io
    port: 6379
    password: carming123
    sentinel:
      password: carming123
      username:

  # ddl-auto: create -> Entity에 맞게 자동으로 테이블 및 필드 생성 [배포에선 사용 X]
  # show-sql: true -> 해당하는 query를 보여줌 (JPA N + 1 문제 확인용) [배포에선 사용 X]
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # paging index를 들어올 때 1부터 시작하는 설정
  data:
    web:
      pageable:
        one-indexed-parameters: true
server:
  port: 5000

# naver-sms
#key:
#  service: ncp:sms:kr:297853391013:carming
#  access: cAeEXzNhz9oRCqJJJlcr
#  secret: lKl7HkNpeuwjP9U6W6FIZJxja5edE4mLMY4fFimj